In [1]:
#import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#load dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df_original  = df

In [3]:
id(df_original) == id(df)

True

In [6]:
df_new = df.copy()

In [7]:
id(df_new) == id (df)

False

In [11]:
df_new.sample(5) #random sample everytime

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
197674,Senior Data Engineer,Senior Data Engineer,"Berlin, Germany",via Technojobs,Full-time,False,Germany,2023-08-24 15:42:32,True,False,Germany,NaN,NaN,NaN,Understanding Recruitment,"['databricks', 'azure', 'docker', 'kubernetes']","{'cloud': ['databricks', 'azure'], 'other': ['..."
506259,Data Engineer,Data Engineer,France,via The Muse,Full-time,False,France,2023-07-21 11:50:26,True,False,France,NaN,NaN,NaN,EPAM Systems,"['python', 'java', 'sql', 'elasticsearch', 'az...","{'cloud': ['azure', 'databricks'], 'databases'..."
18680,Data Analyst,(Junior) Data Analyst (m/f/d),"Munich, Germany",via Monster.de,Full-time,False,Germany,2023-01-17 13:21:51,True,False,Germany,NaN,NaN,NaN,ParkDepot GmbH,"['python', 'sql', 'windows', 'tableau', 'git']","{'analyst_tools': ['tableau'], 'os': ['windows..."
191315,Data Engineer,Data Engineer,Italy,via Lavoro Trabajo.org,Full-time,False,Italy,2023-07-12 15:14:11,False,False,Italy,NaN,NaN,NaN,Assist Digital,"['sql', 'nosql', 'java', 'python', 'scala', 'r...","{'analyst_tools': ['ssis', 'power bi', 'cognos..."
297889,Data Scientist,Data Scientist & Power BI Specialist Purchasin...,"Timișoara, Romania",via The Muse,Full-time,False,Romania,2023-06-09 17:22:54,False,False,Romania,NaN,NaN,NaN,Continental,"['r', 'python', 'power bi', 'tableau', 'powerp...","{'analyst_tools': ['power bi', 'tableau', 'pow..."

In [ ]:
df_new.sample(5, random_state=42) #same sample everytime

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}